### ISSUE TITLE
Gaussian scripts missing

### ISSUE THREAD

**Issue by MalkinE** [uit-no/hpc-doc#11]
In Gaussian documentation there are several references to scripts, which I could not find:
g03parallel.run, g03serial.run, water.inp 
They used to be available on  /global/apps/gaussian/usage
Espen probably wrote them and should know whether they still exist, are current etc. If they are not, the appropriate rst files describing them will be removed.

**Comment by bast** [comment]
Are the scripts not here now:?
https://source.uit.no/cpe/examplescripts/tree/master/gaussian
[also including @eta000 in the discussion]

**Comment by bast** [comment]
Is this issue still relevant? @eta000

**Comment by bast** [comment]
Issue not relevant anymore since we do not provide Gaussian03.
