### ISSUE TITLE
drop csh add bash 

### ISSUE THREAD

**Issue by sth000** [uit-no/hpc-doc#12]
there is a lot of csh info at the page: 
http://hpc.uit.no/en/latest/guides/linux.html
I suggest that we drop the csh completely and add some lines about bash instead.
The default shell on stallo is bash and can not be changed unless you ask the admin. 
There are only a very few dinosaurs that are still using tcsh and they probably know all this already.

**Comment by bast** [comment]
I agree. I will update the page.
