### ISSUE TITLE
Running tasks in parallel within one job 

### ISSUE THREAD

**Issue by sth000** [uit-no/hpc-doc#15]
the $maxpartasks is not defined in the example at: 
http://hpc-uit.readthedocs.org/en/latest/faq/faq.html#running-tasks-in-parallel-within-one-job

in the old documentation at docs.notur.no we had some example scripts one could download 
http://docs.notur.no/uit/stallo_documentation/user_guide/running-many-short-tasks?searchterm=running+tasks+in

we need to polish this a bit.

**Comment by bast** [comment]
I will take care of this one.
