### ISSUE TITLE
Wrong number of nodes in listing 

### ISSUE THREAD

**Issue by dragz** [uit-no/hpc-doc#20]
We only have 328 SL230 nodes, not 372. Numbers of cores need to be scaled accordingly.

**Comment by MalkinE** [comment]
Fixed.

**Comment by dragz** [comment]
Thanks. But 2x328 is 656 not 752.

And the peak performance is 312 TF/s

>>> 304*16*8*2.6+(328+144)*20*8*2.8
312627.2

**Comment by MalkinE** [comment]
OK. I changed these numbers too. The 332 and 448 Gigaflops/s is correct,
right?

**Comment by dragz** [comment]
Thx. Yes, the other numbers are correct.
