### ISSUE TITLE
List of environment variables visible to a job

### ISSUE THREAD

**Issue by mathiasbockwoldt** [uit-no/hpc-doc#21]
It would be nice to have list of environment variables that are visible to a job, maybe with some default value. I mean things like `$SLURM_JOBID` or `$SLURM_ARRAY_TASK_ID`. Is there e.g. a variable for the global working directory? I saw that there is a folder made for every job in `/global/work/${USER}/` but is the folder name in some variable? Or do I have to create the variable myself?
I guess, there are lists with SLURM variables around on the web, but I thought it would be good to have it all on one spot, maybe including Stallo/Notur/Sigma2-specific variables as well.

**Comment by eta000** [comment]
As previously; send this to support-uit@notur.no

Fra: Mathias Bockwoldt <notifications@github.com>
Svar til: uit-no/hpc-doc <reply@reply.github.com>
Dato: torsdag 10. november 2016 14.36
Til: uit-no/hpc-doc <hpc-doc@noreply.github.com>
Emne: [uit-no/hpc-doc] List of environment variables visible to a job (#21)


It would be nice to have list of environment variables that are visible to a job, maybe with some default value. I mean things like $SLURM_JOBID or $SLURM_ARRAY_TASK_ID. Is there e.g. a variable for the global working directory? I saw that there is a folder made for every job in /global/work/${USER}/ but is the folder name in some variable? Or do I have to create the variable myself?
I guess, there are lists with SLURM variables around on the web, but I thought it would be good to have it all on one spot, maybe including Stallo/Notur/Sigma2-specific variables as well.

**Comment by mathiasbockwoldt** [comment]
ok, I just thought that this would be more of a documentation issue, so I put it here. But I will happily send it to the support email address. Same goes for the other issue (#22).
I will leave it up to you to close this (and the other) issue or leave it open depending on your internal workflows.

**Comment by eta000** [comment]
We have stuff like that in place, but all common stuff would - for general workflow reasons - better be adressed to support than to individual recipient.

Regards

Et.

Fra: Mathias Bockwoldt <notifications@github.com>
Svar til: uit-no/hpc-doc <reply@reply.github.com>
Dato: torsdag 10. november 2016 15.04
Til: uit-no/hpc-doc <hpc-doc@noreply.github.com>
Kopi: Espen Tangen <espen.tangen@uit.no>, Comment <comment@noreply.github.com>
Emne: Re: [uit-no/hpc-doc] List of environment variables visible to a job (#21)


ok, I just thought that this would be more of a documentation issue, so I put it here. But I will happily send it to the support email address. Same goes for the other issue (#22<https://github.com/uit-no/hpc-doc/issues/22>).
I will leave it up to you to close this (and the other) issue or leave it open depending on your internal workflows.

**Comment by bast** [comment]
Thanks! I think it is good that you have submitted them and we can keep them here.

**Comment by bast** [comment]
Good idea. We are working on it.
