### ISSUE TITLE
Log of run

### ISSUE THREAD

**Issue by mathiasbockwoldt** [uit-no/hpc-doc#22]
Is it possible to have some kind of log of any given run on Stallo (or other Norwegian clusters)? Good would be some kind of summary appended to the SLURM-log (`slurm-xxx.out`) with the actual time used, maximum memory consumption, maximum CPUs used etc.
Even better would be a more detailed analysis of the run with values for the parameters named above every x seconds.
I wrote a tiny script some time ago for my local computer to monitor and log memory consumption and CPU business. Happy to share it if anyone is interested :smiley:

**Comment by bast** [comment]
I am closing this ticket here because it is IMO missing functionality first and missing documentation second. We are tracking this issue internally though and plan for it.
