### ISSUE TITLE
Link to system log not working

### ISSUE THREAD

**Issue by MalkinE** [uit-no/hpc-doc#7]
On the page http://hpc-uit.readthedocs.org/en/latest/news/news.html there is a link to system log http://stallo-adm.uit.no/wordpress/ , which gives a 403 error (permission denied).

**Comment by bast** [comment]
@sth000 is this something that still exists or some outdated URL that we tried to link to?

**Comment by bast** [comment]
Seems to be fixed by now. Closing.
