### ISSUE TITLE
writing-support-requests: 3-point summary

### ISSUE THREAD

**Issue by rkdarst** [uit-no/hpc-doc#79]
hpc-doc/help/writing-support-requests.rst is one of my favorite things, but it's a bit too long to be linkable when someone has an issue and is honestly trying their best.  I distilled it down to a 3-point list that isn't so condescending I can use as a link in a reply:
  https://scicomp.aalto.fi/triton/help.html#give-enough-information

What do you think?

**Comment by bast** [comment]
It's very good. Can I use that one also on our side?

At some point we will phase this documentation here out (at some point this machine will be phased out) and it continues living here:
https://documentation.sigma2.no/help/how_to_write_good_support_requests.html

Can I use your text here:
https://documentation.sigma2.no/help/support.html

And link to your page? (I know not everything is great on https://documentation.sigma2.no, I am working on improving that this week)

**Comment by rkdarst** [comment]
Absolutely you can use it (it's cc-by but you don't need to be
constricted by that).  We can work on a text suitable for a canned
reply, and update our text too.  I have a feeling there are some
subtle improvements to be done still...

**Comment by bast** [comment]
Great! I will add it on our side, maybe find an improvement, and notify you once it's up.

**Comment by bast** [comment]
As a thank you I will send you a PR.

**Comment by bast** [comment]
- https://documentation.sigma2.no/help/support.html#give-enough-information
- https://github.com/AaltoScienceIT/scicomp-docs/pull/56

Thanks again!
