### ISSUE TITLE
"getting started" link

### ISSUE THREAD

**Issue by MalkinE** [uit-no/hpc-doc#8]
On page http://hpc-uit.readthedocs.org/en/latest/general_info.html there is a <./getting_access> place holder, which does not point to anything. To local users we send the link https://uit.no/ansatte/organisasjon/artikkel?p_document_id=299809&p_dimension_id=88223&p_menu=49281 , but it seems also outdated. Can we put up somewhere a new form? Also, is this https://www.metacenter.no/mas/application/project/pl/ a good link for the national applicants? Or is this better: https://www.notur.no/national-access ?

**Comment by bast** [comment]
I suggest to be pragmatic and link to your suggestions 1 and 3. The form we need to update later. This issue should not wait for the new form to be up.

**Comment by sth000** [comment]
We don't have anything better for the local form. The best would be to create a new form.

the official link for applying for national compute time is on the page:

https://www.metacenter.no/mas/application/project/


new notur.no site will be: http://www.sigma2.no

I don't know if they will change the http://www.sigma2.no to http://www.notur.no at a given time,

but I hope so.


Steinar


________________________________
Fra: MalkinE <notifications@github.com>
Sendt: 28. september 2015 15:46
Til: uit-no/hpc-doc
Emne: [hpc-doc] "getting started" link (#8)


On page http://hpc-uit.readthedocs.org/en/latest/general_info.html there is a <./getting_access> place holder, which does not point to anything. To local users we send the link https://uit.no/ansatte/organisasjon/artikkel?p_document_id=299809&p_dimension_id=88223&p_menu=49281 , but it seems also outdated. Can we put up somewhere a new form? Also, is this https://www.metacenter.no/mas/application/project/pl/ a good link for the national applicants? Or is this better: https://www.notur.no/national-access ?

-
