### ISSUE TITLE
Metasenter page on X-server for Windows link not working

### ISSUE THREAD

**Issue by MalkinE** [uit-no/hpc-doc#9]
In FAQs there is a link to "Metasenter page on X-server for Windows":  <../../../metacenter/metacenter-documentation/metacenter_user_guide/x-server-for-windows>
It came from http://hpc.uit.no/docs/guides/... , but the link doesn't work any more. Shall we just remove it?

**Comment by bast** [comment]
I also think we should just remove it.

**Comment by MalkinE** [comment]
Removed.
